### ISSUE TITLE
Windows release marked as malicious

### ISSUE THREAD

**Issue by matrix07012** [IchBinLeoon/hanime#5]
Just to let you know, total of 10 antiviruses on Virustotal mark the Windows 1.0.3 release as malicious

[https://www.virustotal.com/gui/file/a3b214d77091926b57a912c9ee5cefb6cff42eccfe502d21ef3080cce38afb4d/detection](https://www.virustotal.com/gui/file/a3b214d77091926b57a912c9ee5cefb6cff42eccfe502d21ef3080cce38afb4d/detection)

**Comment by bytedream** [comment]
I've heart that more and more malware writers are switching to no-so-common virus languages like go, so some normal / harmless instructions (in the context of this package) may be flagged as virus typical and because of this the results comes about. Or it's just a windows thing

**Comment by IchBinLeoon** [comment]
Thanks for the info. I tested a few more .exe files from other projects and the result was the same problem. Even a simple "hello world" was flagged as malicious. All .exe files were build on Linux.

**Comment by IchBinLeoon** [comment]
If you build it on a windows vm, it will also be flagged as malicious. Looks like some AVs on VirusTotal are giving false positives. If you don't want to use the pre-built executable for this reason, you can simply clone the repo and build the cli yourself.
