### ISSUE TITLE
New issue, No such host

### ISSUE THREAD

**Issue by YourNekoWaifu** [IchBinLeoon/hanime#8]
Get "https://weeb.hanime.tv/weeb-api-cache/api/v8/m3u8s/58974": dial tcp: lookup weeb.hanime.tv: no such host

Get this every time I try hanime get https://hanime.tv/videos/hentai/ishuzoku-reviewers-8 + more -o \\<ip>\nas\
Good luck man

**Comment by IchBinLeoon** [comment]
Same as in #7. 1.0.5 fixes the issue, but 1080p video downloads are no longer possible.

**Comment by YourNekoWaifu** [comment]
I did update it, to the new version, do i need to specify 720p videos?

**Comment by YourNekoWaifu** [comment]
Okay, need to specify the 720

**Comment by YourNekoWaifu** [comment]
Nope, still doesnt work

**Comment by IchBinLeoon** [comment]
You don't need to, every video is now downloaded in 720p by default instead of 1080p. Are you sure you are using the latest version?

**Comment by YourNekoWaifu** [comment]
1.0.5?

**Comment by YourNekoWaifu** [comment]
let me double check its executing the right file

**Comment by YourNekoWaifu** [comment]
Nope, still not working, they did just release that episode though

**Comment by IchBinLeoon** [comment]
Still the same issue?

**Comment by YourNekoWaifu** [comment]
Yes

**Comment by IchBinLeoon** [comment]
Then you are still using an older version than 1.0.5. Try `hanime -v`.

**Comment by YourNekoWaifu** [comment]
Nice, i am still using the older version FUCK
sorry man

**Comment by YourNekoWaifu** [comment]
Thanks for for doing gods work
